### PR TITLE
Added some ghost blocks for a better experience

### PR DESCRIPTION
**Pull request by kiki-lee**
Added more blocks to the toolbox with a ghost command, hopefully fixing the missing blocks in step 10.

### CODE REVIEW

**Comment by shakao** [comment]
looks like the same ```ghost section got added twice?

**Comment by kiki-lee** [comment]
> looks like the same ```ghost section got added twice?

The documentation says that ```ghost only adds the blocks to the level where you put them, so I added it to the last two.
Is that not the case?

**Comment by shakao** [comment]
oops yeah, looks like that documentation is wrong. we don't filter the toolbox between steps, so all blocks for a tutorial are always available in every step, including ghost blocks

**Comment by kiki-lee** [comment]
> oops yeah, looks like that documentation is wrong. we don't filter the toolbox between steps, so all blocks for a tutorial are always available in every step, including ghost blocks

@shakao   Cool beans.  I fixed.

**Review by shakao — APPROVED** [review]

**Pull request merged**
